### ISSUE TITLE
unable to configure specific project frpm our Azure DevOps organization 

### ISSUE THREAD

**Issue by praptipatel90** [microsoft/azure-pipelines-jira#24]
**Describe the bug**
We are unable to configure specific project in our Azure DevOps organization because I am not able to select it from the drop-down menu. All existing Project do show up in dropdown, but I am not able to select it to be able to connect to/with jira. 

**To Reproduce**
1.	Install Azure Pipelines for Jira in Jira Cloud
2.	Click on 'Add Organization'
3.	Select organization
4.	Try selecting project from dropdown but it’s not being accepted. (See below screen shot)

![1](https://user-images.githubusercontent.com/29693645/67126727-ca83d700-f1c5-11e9-985c-8498ee20d6b4.PNG)

![2](https://user-images.githubusercontent.com/29693645/67126734-d2dc1200-f1c5-11e9-8092-b4b440589bd1.png)

**Expected behavior**
Populate selected project from dropdown.

**Comment by rsun11** [comment]
Having the same issue. Clicking continue will automatically select the first project in your drop down list. Tried submitting the same request in POSTMAN with the proper project Id and it'll add the service connection to devops, but I think there's another request to JIRA to add the organization/project because the integration isn't working properly with this method.

**Comment by nealAR** [comment]
Same issue here. I tried the method listed above by @rsun11 but I'm getting the response `The token is expired`. Is anyone on the Jira or MS side working on this?

**Comment by vithati** [comment]
@praptipatel90 , We have fixed the issue. Can you please try once again.
