### ISSUE TITLE
Get started results in "App is not responding" message being displayed indefinitely

### ISSUE THREAD

**Issue by spr0ut** [microsoft/azure-pipelines-jira#6]
**Describe the bug**
Once installed, clicking the Get started button results in the message 
"App is not responding. Wait or cancel?" 
being displayed indefinitely.

**To Reproduce**
- Install app
- Wait for install to complete
- Click get started
- Observe message

**Expected behavior**
Some configuration screen should load.

**Screenshots**
![image](https://user-images.githubusercontent.com/30391853/60345986-1e1dab00-99b2-11e9-8d94-25d690d34152.png)

Uninstalling and reinstalling resulted in the same behaviour.

User account installing the application is both a JIRA admin and Azure Devops org admin.

**Comment by spr0ut** [comment]
Can someone respond to this issue please? @shashban / @shyama1208

**Comment by shashban** [comment]
@prativen for diagnosis of the issue

**Comment by prativen** [comment]
@spr0ut Apologize for having missed this. Can you send us a [HAR file](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting) for your session to help us diagnose the issue you are facing.

**Comment by spr0ut** [comment]
It appears a recent update has resolved this issue.

**Comment by sanjusoftware** [comment]
doesn't look like this issue is resolved yet. I am facing the same issue today. After multiple install / un install / reinstall cycles, I am still getting the same message even after waiting for more than 30 mins... please help me resolve this issue.
- I have jira cloud instance
- I installed the plugin and hit Getting Started
- no progress after that and keep seeing the following page:

![image](https://user-images.githubusercontent.com/232573/78745718-97571f00-7982-11ea-89eb-2195b69c98cb.png)

**Comment by andyworsley** [comment]
I had the same issue as @sanjusoftware today.

**Comment by andyworsley** [comment]
@shashban Done, here is the problem I have reported: https://developercommunity.visualstudio.com/content/problem/988244/azure-pipelines-for-jira-hangs-at-get-started-conf.html. Can you please expedite the problem, as I am keen to get this working ASAP?

**Comment by andyworsley** [comment]
@shashban Looks like this has been reraised as #33.
